version: '3'
services:
  alpha:
    container_name: alpha
    image: conti-test:1.0
    init: true
    hostname: alpha
    networks:
      web:
        ipv4_address: 172.16.100.140
    healthcheck:
      test: ["CMD", "pwd"]
      interval: 1s
      timeout: 10s
      retries: 30

  bravo:
    container_name: bravo
    image: conti-test:1.0
    init: true
    hostname: bravo
    networks:
      web:
        ipv4_address: 172.16.100.141
    healthcheck:
      test: ["CMD", "pwd"]
      interval: 1s
      timeout: 10s
      retries: 30
    depends_on:
      alpha:
        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          cpus: 0.1
#          memory: 4G

  charlie:
    container_name: charlie
    image: conti-test:1.0
    init: true
    hostname: charlie
    networks:
      web:
        ipv4_address: 172.16.100.142
    healthcheck:
      test: ["CMD", "pwd"]
      interval: 1s
      timeout: 10s
      retries: 30
    volumes:
      - /tmp/charlie-opt-data:/opt/data
    depends_on:
      bravo:
        condition: service_healthy

networks:
  web:
    name: conti-test
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.128/25
          gateway: 172.16.100.129
